# Generated by Django 6.0 on 2025-12-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Ключ сессии')),
                ('file', models.FileField(upload_to='datasets/original/', verbose_name='Оригинальный файл')),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='datasets/processed/', verbose_name='Обработанный файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки')),
            ],
            options={
                'verbose_name': 'Загруженный датасет',
                'verbose_name_plural': 'Загруженные датасеты',
            },
        ),
    ]
